"""
Metadata evidence stream.

This module reads EXIF/XMP via ExifTool and derives *heuristic* feature
flags. Every finding here is unverified — a string in an EXIF field, a
provenance-related tag name, or a binary marker in the file bytes. The
heuristic score treats these as weak evidence only.

For anything that needs to distinguish "the file contains the substring
``c2pa``" from "this image carries a cryptographically valid C2PA
manifest saying it is AI-generated", use
:func:`provenance_validation.validate_provenance` instead — that is the
only place that performs actual C2PA validation.

Semantic corrections vs. the earlier version (see task requirements):

* The mere presence of ``c2pa``, ``claim_generator``, or
  ``created_software_agent`` no longer sets ``has_ai_claim``. Those tag
  names identify software that produced provenance information; they do
  not by themselves mean the image was AI-generated.
* ``has_c2pa`` was renamed ``has_c2pa_marker`` to make its
  "raw indicator, not validation" meaning explicit. It carries no score
  weight — validated provenance is exposed separately on
  :class:`ProvenanceResult`.
* Provider keywords (openai, midjourney, firefly, …) still contribute
  to the heuristic score but are tagged as ``unverified_ai_provider_hints``
  in the surfaced features so downstream consumers see them as such.
* Missing metadata remains a neutral 0.5 (uncertain) — never "real".
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

# Support both `python -m src.genai_detection.metadata_module.metadata_extraction`
# and the documented direct form
# `python src/genai_detection/metadata_module/metadata_extraction.py IMG`.
# In the direct form __package__ is empty, so the relative imports below
# fail with "attempted relative import with no known parent package".
# Fall back to absolute imports after bootstrapping the project root
# onto sys.path — same pattern app.py uses.
try:
    from .models import ProvenanceResult, ProvenanceStatus
    from .provenance_validation import validate_provenance
except ImportError:
    _PROJECT_ROOT = Path(__file__).resolve().parents[3]
    if str(_PROJECT_ROOT) not in sys.path:
        sys.path.insert(0, str(_PROJECT_ROOT))
    from src.genai_detection.metadata_module.models import (  # type: ignore[no-redef]
        ProvenanceResult,
        ProvenanceStatus,
    )
    from src.genai_detection.metadata_module.provenance_validation import (  # type: ignore[no-redef]
        validate_provenance,
    )

# ─── Keyword classes ───────────────────────────────────────────────────────
# Split so the code and the score reflect the semantic distinction:
#
# EXPLICIT_AI_KEYWORDS   — natural-language phrases that name AI content
#                          outright ("ai generated", "generated by ai").
# AI_PROVIDER_KEYWORDS   — commercial AI-image services. Presence in
#                          metadata is a strong-but-not-cryptographic hint
#                          (an editor could paste the string). Treated as
#                          unverified provider hints for scoring.
# PROVENANCE_METADATA_KEYS — tags/strings related to C2PA/Content
#                          Credentials plumbing. They identify the
#                          provenance system, NOT the origin of the
#                          content: a camera-signed image and an AI image
#                          both contain these strings.
# AMBIGUOUS_AI_HINTS     — dictionary words that CAN indicate AI content
#                          but frequently appear in unrelated contexts
#                          ("synthetic dataset", "synthetic material").
#                          Never a standalone AI claim.

EXPLICIT_AI_KEYWORDS: list[str] = [
    "ai generated",
    "ai-generated",
    "generated by ai",
    "generative ai",
]

AI_PROVIDER_KEYWORDS: list[str] = [
    "openai",
    "dall-e",
    "dalle",
    "chatgpt",
    "stable diffusion",
    "stability ai",
    "midjourney",
    "firefly",
    "adobe firefly",
    "ideogram",
    "flux",
    "runway",
    "leonardo",
    "imagen",
    "grok",
]

PROVENANCE_METADATA_KEYS: list[str] = [
    "c2pa",
    "claim_generator",
    "created_software_agent",
    "content credentials",
    "manifest",
]

AMBIGUOUS_AI_HINTS: list[str] = [
    "synthetic",
]

# Union used for the keyword scan surfaced in the `keyword_hits` list —
# kept for backwards compatibility with the AnalysisResult consumers.
AI_KEYWORDS: list[str] = (
    EXPLICIT_AI_KEYWORDS
    + AI_PROVIDER_KEYWORDS
    + PROVENANCE_METADATA_KEYS
    + AMBIGUOUS_AI_HINTS
)

CAMERA_KEYS = [
    "make",
    "model",
    "lensmodel",
    "lensinfo",
    "focallength",
    "aperturevalue",
    "exposuretime",
    "isospeedratings",
    "makernote",
]

SOFTWARE_KEYS = [
    "software",
    "processingsoftware",
    "creatortool",
    "historysoftwareagent",
    "claim_generator",
    "created_software_agent",
]

C2PA_KEYS = [
    "c2pa",
    "manifest",
    "contentcredentials",
    "claim_generator",
    "created_software_agent",
]

BINARY_MARKERS = [
    b"c2pa",
    b"claim_generator",
    b"created_software_agent",
    b"openai",
    b"dall-e",
    b"dalle",
    b"midjourney",
    b"stable diffusion",
    b"firefly",
    b"ideogram",
    b"flux",
]

# Short/ambiguous keywords ("flux" in "influx", "synthetic" in
# "photosynthetic") must match as whole words, so every keyword is matched
# with word-boundary lookarounds rather than plain substring containment.
_KEYWORD_PATTERNS = {
    kw: re.compile(r"(?<!\w)" + re.escape(kw) + r"(?!\w)") for kw in AI_KEYWORDS
}
_BINARY_MARKER_PATTERNS = {
    marker: re.compile(rb"(?<![0-9a-z_])" + re.escape(marker) + rb"(?![0-9a-z_])")
    for marker in BINARY_MARKERS
}

# Keys that only identify C2PA/Content Credentials plumbing — used to
# split "found a real AI provider name" from "found the string 'c2pa'".
_PROVENANCE_ONLY_KEYS = set(PROVENANCE_METADATA_KEYS)


def _matches_keyword(keyword: str, text: str) -> bool:
    return _KEYWORD_PATTERNS[keyword].search(text) is not None


class FeatureSet(BaseModel):
    """
    Raw, unverified heuristic flags derived from EXIF/XMP/file-bytes.

    Every field describes evidence at the metadata layer only. Nothing
    here is a truth claim about the image's origin — see
    :class:`ProvenanceResult` for cryptographically validated provenance.
    """

    # Pydantic v2: allow ``has_c2pa`` on inbound data as an alias for
    # ``has_c2pa_marker`` so existing callers (tests, notebooks) keep
    # working through the rename. New code should use the new name.
    model_config = ConfigDict(populate_by_name=True)

    has_make: bool = False
    has_model: bool = False
    has_lens_model: bool = False
    has_makernote: bool = False
    has_gps: bool = False

    has_c2pa_marker: bool = Field(default=False, alias="has_c2pa")
    """
    Raw C2PA-related tag or binary marker present. This is a purely
    textual indicator — a valid C2PA manifest carries these strings, but
    so does any file whose bytes happen to contain them. Use
    :class:`ProvenanceResult` to determine whether provenance actually
    validates.
    """

    has_ai_claim: bool = False
    """
    An unambiguous AI-generation signal in the metadata text — either an
    explicit natural-language phrase ("ai generated", "generated by AI")
    or a named commercial AI-image provider (OpenAI, Midjourney, …).

    This is still HEURISTIC: the strings are unverified. Presence of a
    C2PA marker, ``claim_generator``, or ``created_software_agent`` on
    its own does NOT set this field — those strings identify the
    provenance system, not the content's origin.
    """

    has_camera_claim: bool = False
    has_edit_claim: bool = False
    software_tag_count: int = 0
    xmp_namespace_count: int = 0
    keyword_hits: list[str] = Field(default_factory=list)
    binary_hits: list[str] = Field(default_factory=list)

    unverified_ai_provider_hints: list[str] = Field(default_factory=list)
    """AI provider names ("openai", "midjourney", …) found in the raw
    metadata text. Labelled as unverified so consumers do not treat
    them as validated claims."""

    suspicious_only_software_tags: bool = False
    suspicious_perfect_timestamp: bool = False

    # Backwards-compatible read-only alias, so anywhere that previously
    # read ``features.has_c2pa`` keeps working after the rename. The
    # canonical field is ``has_c2pa_marker`` — prefer it in new code.
    @property
    def has_c2pa(self) -> bool:  # pragma: no cover - trivial
        return self.has_c2pa_marker


class AnalysisResult(BaseModel):
    file: str
    metadata_extracted: bool
    metadata_summary: dict[str, Any]
    features: FeatureSet
    provenance: ProvenanceResult
    """C2PA validation result — separate evidence, not folded into
    ``ai_probability``. Consult ``provenance.status`` before interpreting
    the other provenance fields."""
    ai_probability: float
    decision: str
    rationale: list[str]


def run_exiftool(image_path: Path) -> dict[str, Any]:
    cmd = [
        "exiftool",
        "-j",
        "-a",
        "-u",
        "-g1",
        str(image_path),
    ]

    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        check=False
    )

    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or "ExifTool failed")

    data = json.loads(result.stdout)
    if not data:
        return {}
    return data[0]


def flatten_metadata(data: Any, prefix: str = "") -> dict[str, str]:
    flat: dict[str, str] = {}

    if isinstance(data, dict):
        for key, value in data.items():
            new_prefix = f"{prefix}.{key}" if prefix else str(key)
            flat.update(flatten_metadata(value, new_prefix))
    elif isinstance(data, list):
        for i, value in enumerate(data):
            new_prefix = f"{prefix}[{i}]"
            flat.update(flatten_metadata(value, new_prefix))
    else:
        flat[prefix.lower()] = str(data).lower()

    return flat


def scan_binary_markers(image_path: Path) -> list[str]:
    try:
        blob = image_path.read_bytes().lower()
    except Exception:
        return []

    hits = []
    for marker, pattern in _BINARY_MARKER_PATTERNS.items():
        if pattern.search(blob):
            hits.append(marker.decode("utf-8", errors="ignore"))
    return sorted(set(hits))


def find_keyword_hits(flat: dict[str, str]) -> list[str]:
    haystack = " ".join([f"{k} {v}" for k, v in flat.items()])
    hits = [kw for kw in AI_KEYWORDS if _matches_keyword(kw, haystack)]
    return sorted(set(hits))


def count_xmp_namespaces(flat: dict[str, str]) -> int:
    namespaces = set()
    for key in flat:
        if "xmp" in key:
            first = key.split(".")[0]
            namespaces.add(first)
    return len(namespaces)


def looks_like_perfect_timestamp(flat: dict[str, str]) -> bool:
    patterns = [
        r"\b\d{4}:\d{2}:\d{2} \d{2}:00:00\b",
        r"\b\d{4}-\d{2}-\d{2}t\d{2}:00:00\b",
    ]
    for value in flat.values():
        for pattern in patterns:
            if re.search(pattern, value):
                return True
    return False


def _has_meaningful_gps_value(value: str) -> bool:
    """True only for GPS values carrying actual data — empty or all-zero coordinates don't count."""
    return bool(re.search(r"[1-9]", value))


def _detect_provider_hits(values: str) -> list[str]:
    """AI provider names present in the flattened metadata text."""
    return [kw for kw in AI_PROVIDER_KEYWORDS if _matches_keyword(kw, values)]


def build_features(flat: dict[str, str], binary_hits: list[str]) -> FeatureSet:
    keys = set(flat.keys())
    values = " ".join(flat.values())

    has_make = any("make" in k and "makernote" not in k and flat[k].strip() for k in keys)
    has_model = any(
        ("model" in k and "lens" not in k and flat[k].strip())
        for k in keys
    )
    has_lens_model = any("lensmodel" in k or "lensinfo" in k for k in keys)
    has_makernote = any("makernote" in k for k in keys)
    has_gps = any(
        "gps" in k and "version" not in k and _has_meaningful_gps_value(flat[k])
        for k in keys
    )

    # "C2PA marker" = a raw indicator only. Presence of these tags does
    # NOT mean the image is AI-generated (a camera signing its own image
    # with C2PA writes the same tag names). Validated provenance is
    # reported separately on ProvenanceResult.
    has_c2pa_marker = (
        any(any(tag in k for tag in C2PA_KEYS) for k in keys)
        or _matches_keyword("c2pa", values)
    )

    # Narrowed AI claim: an unambiguous natural-language AI phrase OR a
    # commercial AI-image provider name. `claim_generator`,
    # `created_software_agent`, `c2pa` and `content credentials` are
    # EXPLICITLY excluded here — they identify provenance plumbing, not
    # the origin of the content.
    provider_hits = _detect_provider_hits(values)
    binary_provider_hits = [
        b for b in binary_hits
        if b not in _PROVENANCE_ONLY_KEYS and b in AI_PROVIDER_KEYWORDS
    ]
    combined_provider_hits = sorted(set(provider_hits + binary_provider_hits))
    has_explicit_ai_phrase = any(_matches_keyword(x, values) for x in EXPLICIT_AI_KEYWORDS)
    has_ai_claim = has_explicit_ai_phrase or bool(combined_provider_hits)

    # Tag-name based, not substring-of-any-value: "Camera Raw" (an Adobe
    # editor) in a software tag must not count as a camera-capture claim.
    has_camera_claim = has_make or has_model or has_lens_model or has_makernote
    has_edit_claim = "edited" in values or "photoshop" in values or "lightroom" in values

    software_tag_count = sum(
        1 for k in keys if any(tag in k for tag in SOFTWARE_KEYS)
    )

    suspicious_only_software_tags = (
        software_tag_count > 0
        and not has_make
        and not has_model
        and not has_lens_model
        and not has_makernote
    )

    return FeatureSet(
        has_make=has_make,
        has_model=has_model,
        has_lens_model=has_lens_model,
        has_makernote=has_makernote,
        has_gps=has_gps,
        has_c2pa_marker=has_c2pa_marker,
        has_ai_claim=has_ai_claim,
        has_camera_claim=has_camera_claim,
        has_edit_claim=has_edit_claim,
        software_tag_count=software_tag_count,
        xmp_namespace_count=count_xmp_namespaces(flat),
        keyword_hits=find_keyword_hits(flat),
        binary_hits=binary_hits,
        unverified_ai_provider_hints=combined_provider_hits,
        suspicious_only_software_tags=suspicious_only_software_tags,
        suspicious_perfect_timestamp=looks_like_perfect_timestamp(flat),
    )


def score_features(features: FeatureSet) -> tuple[float, list[str]]:
    """
    Heuristic ``P(AI)`` from the raw metadata evidence.

    Missing metadata → 0.50 (uncertain), by design. The score is capped
    to ``[0.01, 0.99]`` to keep it a probability.

    Note: this scorer intentionally treats the raw ``has_c2pa_marker``
    as *descriptive only* — a C2PA marker is not proof of AI generation
    and adds 0 to the score. Cryptographically validated provenance is
    surfaced separately on :class:`ProvenanceResult` and is not folded
    into ``P(AI)_m`` in this task (see the task brief: "expose
    provenance as a separate evidence object first and document the
    limitation instead of inventing weights").
    """

    score = 0.50
    rationale: list[str] = []

    if features.has_ai_claim:
        score += 0.35
        rationale.append(
            "Explicit AI-related generator or provenance signal found — heuristic, unverified."
        )

    if features.has_c2pa_marker:
        # No score change: a C2PA marker is a raw indicator, not proof
        # of AI generation. See ProvenanceResult for validated status.
        rationale.append(
            "C2PA/content-credentials marker present — descriptive only; verify with the provenance validator."
        )

    if features.keyword_hits:
        score += min(0.20, 0.03 * len(features.keyword_hits))
        rationale.append(
            f"AI/provenance keyword hits (heuristic, unverified): {', '.join(features.keyword_hits)}"
        )

    if features.binary_hits:
        score += min(0.15, 0.03 * len(features.binary_hits))
        rationale.append(
            f"Binary marker hits (heuristic, unverified): {', '.join(features.binary_hits)}"
        )

    if features.suspicious_only_software_tags:
        score += 0.10
        rationale.append("Software tags present without normal camera metadata.")

    if features.suspicious_perfect_timestamp:
        score += 0.05
        rationale.append("Timestamp pattern looks unusually clean/perfect.")

    camera_evidence_count = sum([
        features.has_make,
        features.has_model,
        features.has_lens_model,
        features.has_makernote,
    ])

    # NB: rich camera EXIF is a WEAK reason to lean towards camera
    # origin, not proof of authenticity. EXIF is easy to fabricate; this
    # scorer only nudges the probability, never asserts authenticity.
    if camera_evidence_count >= 3:
        score -= 0.20
        rationale.append(
            "Rich camera metadata present — indicator only, EXIF fields can be fabricated."
        )
    elif camera_evidence_count == 2:
        score -= 0.10
        rationale.append(
            "Some camera metadata present — indicator only, EXIF fields can be fabricated."
        )

    score = max(0.01, min(0.99, score))

    return score, rationale


def decide(prob: float, features: FeatureSet) -> str:
    if features.has_ai_claim and prob >= 0.70:
        return "likely_ai_generated"
    if prob >= 0.80:
        return "likely_ai_generated"
    if prob <= 0.40:
        return "likely_camera_origin"
    return "uncertain"


def analyse_image(image_path: str) -> AnalysisResult:
    path = Path(image_path)
    if not path.exists():
        raise FileNotFoundError(f"File not found: {image_path}")

    try:
        raw_metadata = run_exiftool(path)
        metadata_extracted = True
    except Exception as exc:
        raw_metadata = {"error": str(exc)}
        metadata_extracted = False

    flat = flatten_metadata(raw_metadata)
    binary_hits = scan_binary_markers(path)
    features = build_features(flat, binary_hits)
    ai_probability, rationale = score_features(features)
    decision = decide(ai_probability, features)

    # Cryptographic provenance validation runs independently of the
    # heuristic scoring. Never raises — errors surface as a ProvenanceStatus.
    try:
        provenance = validate_provenance(path)
    except Exception as exc:
        # Belt-and-braces: validate_provenance already returns errors as
        # a status, but if some future change makes it raise we still
        # produce a well-formed AnalysisResult.
        provenance = ProvenanceResult(
            status=ProvenanceStatus.ERROR,
            rationale="Provenance validator raised an unexpected exception.",
            validation_errors=[f"{type(exc).__name__}: {exc}"],
        )

    summary = {
        "top_level_keys": sorted(list(raw_metadata.keys()))[:20] if isinstance(raw_metadata, dict) else [],
        "keyword_hits": features.keyword_hits,
        "binary_hits": features.binary_hits,
        "unverified_ai_provider_hints": features.unverified_ai_provider_hints,
    }

    return AnalysisResult(
        file=str(path),
        metadata_extracted=metadata_extracted,
        metadata_summary=summary,
        features=features,
        provenance=provenance,
        ai_probability=round(ai_probability, 4),
        decision=decision,
        rationale=rationale,
    )


def analyse_folder(folder_path: str, extensions: tuple[str, ...] = (".jpg", ".jpeg", ".png", ".webp")):
    folder = Path(folder_path)
    results = []
    for file in sorted(folder.iterdir()):
        if file.suffix.lower() in extensions:
            try:
                results.append(analyse_image(str(file)).model_dump())
            except Exception as exc:
                results.append({"file": str(file), "error": str(exc)})
    return results


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python metadata_extraction.py <image_path>")
        sys.exit(1)

    try:
        res = analyse_image(sys.argv[1])
        print(json.dumps(res.model_dump(), indent=2))
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)
